name: Fist workflow
on: workflow_dispatch
jobs:
  first-job: 
    runs-on: ubuntu-latest
    steps:
      - name: Print greeting
        run: echo 'hello world'
      - name: Print goodbye
        run: echo "bye $(date '+%Y-%m-%d')"
